DjangoTests/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name="detail"),
    url(r'collection/add/$', views.CollectionCreate.as_view(), name='collection-add'),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Collection(models.Model):
    artist = models.CharField(max_length=100)
    title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + ", " + self.artist


class Song(models.Model):
    # CASCADE: if album of a particular song is deleted, then the song will also be deleted
    album = models.ForeignKey(Collection, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title

music/views.py
from django.views import generic
from music.models import Collection
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_collections'

    def get_queryset(self):
        return Collection.objects.all()


class DetailView(generic.DetailView):
    model = Collection
    template_name = 'music/detail.html'


class CollectionCreate(CreateView):
    model = Collection
    fields = ['artist', 'title', 'genre', 'album_logo']

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}DjangoTests{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">DjangoTests</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">

                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                            Collections
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                            Songs
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:collection-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Add Collection
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            Logout
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/collection_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Collection!{% endblock %}

{% block body %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'music/form-template.html' %}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock %}

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Collection Details{% endblock %}

{% block body %}
    <img src="{{ collection.album_logo }}">

    <h1>{{ collection.title }}</h1>
    <h2>{{ collection.artist }}</h2>

    {% if error_message %}
        <span><strong>{{ error_message }}</strong></span>
    {% endif %}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

    <ul>
        {% for album in all_collections %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.title }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}